name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@6c5ccdad469c9f8a2996bfecaec55a631a347034
